on:
  push:
    branches:
      - master

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "gifski", "glue"), dependencies = TRUE)'
      - name: Render READMEs
        run: |
          rmarkdown::render("README.Rmd", output_format = "github_document")
          rmarkdown::render("PNG/README.Rmd", output_format = "github_document")
        shell: Rscript {0}
      - name: Push results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git commit hex-stickers.gif -m 'Re-build README.Rmd' || echo "No changes to commit"
          git commit PNG/README.md -m 'Re-build PNG/README.Rmd' || echo "No changes to commit"
          git config --global user.name "${{secrets.NAME}}"
          git config --global user.email ${{secrets.EMAIL}}
          git push origin master || echo "No changes to commit"
