on:
  push:
    branches:
      - master

name: Render README

jobs:
  render:
    name: Render README
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: install cargo
        runs: |
          apt-get update
          apt-get install -y --no-install-recommends cargo
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "gifski", "glue"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Render README PNG
        run: Rscript -e 'rmarkdown::render("PNG/README.Rmd")'
      - name: Render README SVG
        run: Rscript -e 'rmarkdown::render("SVG/README.Rmd")'
      - name: Commit results
        run: |
          git commit README.md PNG/README.Rmd SVG/README.Rmd -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
