on:
  push:
    branches:
      - main

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::gifski
            any::glue
            any::magick
      - name: Render READMEs
        run: rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}
      - name: Push results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add thumbs/* || echo "No new thumbs"
          git commit -m 'new thumbs' || echo "No changes to commit"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git commit hex-stickers.gif -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
